export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  COLLEGE_ADMIN = 'COLLEGE_ADMIN',
  HOD = 'HOD',
  FACULTY = 'FACULTY',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
  FINANCE_STAFF = 'FINANCE_STAFF',
  HR_STAFF = 'HR_STAFF',
  LIBRARIAN = 'LIBRARIAN',
  HOSTEL_WARDEN = 'HOSTEL_WARDEN',
  PLACEMENT_OFFICER = 'PLACEMENT_OFFICER',
  EXAM_CONTROLLER = 'EXAM_CONTROLLER',
}

export enum StudentStatus {
  APPLIED = 'APPLIED',
  ADMITTED = 'ADMITTED',
  ENROLLED = 'ENROLLED',
  SEMESTER_BREAK = 'SEMESTER_BREAK',
  GRADUATED = 'GRADUATED',
  DROPOUT = 'DROPOUT',
  SUSPENDED = 'SUSPENDED',
  EXPELLED = 'EXPELLED',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum Category {
  GENERAL = 'GENERAL',
  OBC = 'OBC',
  SC = 'SC',
  ST = 'ST',
  EWS = 'EWS',
  PWD = 'PWD',
}

export enum ApplicationStatus {
  PENDING = 'PENDING',
  REVIEWING = 'REVIEWING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WAITLISTED = 'WAITLISTED',
}

export enum TransactionStatus {
  INITIATED = 'INITIATED',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum DocumentStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}
