export const ErrorCodes = {
  // Auth Errors
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INSUFFICIENT_PERMISSION: 'AUTH_INSUFFICIENT_PERMISSION',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',

  // Student Errors
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  STUDENT_DUPLICATE_ENROLLMENT: 'STUDENT_DUPLICATE_ENROLLMENT',

  // Fee Errors
  FEE_ALREADY_PAID: 'FEE_ALREADY_PAID',
  FEE_PAYMENT_FAILED: 'FEE_PAYMENT_FAILED',
  FEE_INSUFFICIENT_AMOUNT: 'FEE_INSUFFICIENT_AMOUNT',

  // Attendance Errors
  ATT_ALREADY_MARKED: 'ATT_ALREADY_MARKED',
  ATT_LOCKED: 'ATT_LOCKED',

  // Exam Errors
  EXM_ELIGIBILITY_FAILED: 'EXM_ELIGIBILITY_FAILED',
  EXM_MARKS_OUT_OF_RANGE: 'EXM_MARKS_OUT_OF_RANGE',

  // General Errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = keyof typeof ErrorCodes;
